### ISSUE TITLE
Update CDNO/tooling to lastest owl API

### ISSUE THREAD

**Issue by kaiiam** [CompositionalDietaryNutritionOntology/cdno#113]
In case anyone on the team missed it, there's been a rather large update to all the relevant tools ROBOT 1.9.3, ODK 1.4 and Protégé 5.6.1, all of which are now using the  new version of the OWL API, 4.5.25. 

The instructions from the OBO community slack message were to
1. (When using ODK), pull the latest image and update your repository as per the usual procedure. Once the repository is updated, you might want to try a “mock release” and carefully check all the generated files.
2. Open your main ontology file (the “-edit” file, if you’re using an ODK-based layout) with the new version of Protégé and forcefully save it, without introducing any ontological change.
3. Commit the newly saved -edit file.
4. From that moment on, the edit file should never again be edited with Protégé < 5.6.0, so if your ontology is worked on by several people, make sure they all upgrade their version of Protégé.

No rush on this, but we'll need to do this prior to doing anything else with CDNO. Thankfully we don't have any outstanding Pull Requests.

**Comment by LilyAndres** [comment]
Great, thanks @kaiiam I will work on this tomorrow.

**Comment by kaiiam** [comment]
No rush we just need to eventually handle this I haven't updated my systems yet.

**Comment by LilyAndres** [comment]
Hey @kaiiam I was wondering if you have experienced this issue when you update Protégé and you can't visualise the ontology from the local repo (see figure below)

<img width="1296" alt="Screen Shot 2023-03-27 at 8 26 32 pm" src="https://user-images.githubusercontent.com/25215773/227900696-657cbf3f-173a-402b-896a-a8de13a9c8f1.png">

But when I use a URL for example from FoodOn http://purl.obolibrary.org/obo/foodon.owl I get this:

<img width="1317" alt="Screen Shot 2023-03-27 at 8 39 20 pm" src="https://user-images.githubusercontent.com/25215773/227902889-e73d0153-49a9-4572-8481-f5dac709649e.png">

Maybe I didn't upgrade it properly...

**Comment by LilyAndres** [comment]
Thanks @kaiiam, that worked. It just doesn't work when I try to open it from the console, example:

 cdno git:(master) open cdno.owl

Anyway, I have a more important question. I followed your instructions  "pull the latest image (with docker pull obolibrary/odkfull) and update the repo as per the usual procedure (Intermediate CDNO Compile Instructions)", thanks. But, with the next step:

> 2. Open your main ontology file (the “-edit” file, if you’re using an ODK-based layout) with the new version of Protégé and forcefully save it, without introducing any ontological change.

I wonder if when you say "save it, without introducing any ontological change", means I can't delete terms that appear in the cdno.owl file and that were highlighted by Damion in issue #101 

<img width="1260" alt="Screen Shot 2023-03-31 at 1 56 18 pm" src="https://user-images.githubusercontent.com/25215773/229011011-f6760461-bfe7-4dc8-bc44-5487266461d0.png">

When I run all the compile instructions I have to delete the equivalent relationships of these terms in the cdno-edit.owl file using Protégé. So, this means I can't do this and save the edit file and then run the release command? 

I hope this makes sense.

**Comment by kaiiam** [comment]
> "save it, without introducing any ontological change"

Yes literally, the first time when saving with the new version of protege don't change a single thing just press save and then it'll change a bunch of stuff. Once that's done then you can takle other issues. 

To the point about that other issue we shouldn't be deleting EQ axioms in protoge we should deprecate the terms in the relevant template.

**Comment by LilyAndres** [comment]
I did it for the last release. I will close this issue now.
