### ISSUE TITLE
Lignin should be a subclass of insoluble fibre?

### ISSUE THREAD

**Issue by ddooley** [CompositionalDietaryNutritionOntology/cdno#116]
This seems to be a common claim out on the web, e.g. "https://extension.usu.edu/archive/is-all-dietary-fiber-the-same"

**Comment by LilyAndres** [comment]
Hi @ddooley I am working on trying to move the fibre issue to the table with Shavawn, hopefully we can get started with this soon.

**Comment by LilyAndres** [comment]
@recombics Not sure if you have seen this issue...

**Comment by NutrientInstitute** [comment]
Lignin is currently being reviewed by the Dietary Fiber Ontology Working Group. 

In a few weeks, once we have recieved feedback on this term from fiber experts and a concensus has been reached, edits will be made to the placement of this term.

**Comment by LilyAndres** [comment]
This issue has been solved in the latest release, please have a look and let me know if there are any issues that need to be discussed. I will close this issue now.
