### ISSUE TITLE
protein class suggested updates

### ISSUE THREAD

**Issue by recombics** [CompositionalDietaryNutritionOntology/cdno#118]
i) could napin be moved from
  >dietary chemical component
     > protein
to
..
>protein 
   >seed storage protein
         >albumin type

+  could collage, elastin, fibrin lose their capitalization ?

thanks
Graham

**Comment by LilyAndres** [comment]
This issue has been fixed in the new release. The capitalisation can't be fixed because CHEBI has originally the terms with capitals.
