### ISSUE TITLE
CDNO Ontology Description missing from OLS

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#123]
The description for the ontology is not appearing on OLS - see image below for reference.

![image](https://github.com/CompositionalDietaryNutritionOntology/cdno/assets/128626166/1b0e23d3-92e0-4d99-9b94-a40573bd2a10)

**Comment by NutrientInstitute** [comment]
You need to add a description to the [project.yaml](https://github.com/CompositionalDietaryNutritionOntology/cdno/blob/master/project.yaml) file, description is set to none 
![image](https://github.com/CompositionalDietaryNutritionOntology/cdno/assets/128626166/4598083a-b563-43e1-b044-085174ebbcd8)

**Comment by LilyAndres** [comment]
Thanks @NutrientInstitute I hope it fix the issue in OLS. I will close this issue now :)
