### ISSUE TITLE
Suggestion to update template for consistency

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#124]
In the file [nutritional_components_framework.csv](https://github.com/CompositionalDietaryNutritionOntology/cdno/blob/master/src/ontology/templates/nutritional_components_framework.csv) the column `parent class` goes back and forth between reffering to terms using labels and identifiers. For consistency, it would be beneficial replace labels with identifiers in this column.

**Comment by LilyAndres** [comment]
Thanks @NutrientInstitute I fixed this in the new release. I will close this issue now :)
