### ISSUE TITLE
Change parent terms for amino acid

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#126]
At the moment `amino acid` (CHEBI:33709) has parent 'organic acid' (CHEBI:64709), which is accurate. But `organic acid` has parent 'flavanoids' (CHEBI:72544) which in turn has parent  `plant secondary metabolite` (CDNO:0000013). This implies that amino acids are both flavanoids and plant secondary metabolites which does not seem accurate. The terms `amino acid` and `flavanoids` are both imported from ChEBI and they do not share the same relationship they do in CDNO.

I recommend changing the parent term of `organic acid` to `dietary chemical component`.

![image](https://github.com/CompositionalDietaryNutritionOntology/cdno/assets/128626166/5c79f1f3-9216-422a-b8a4-9cf0d2c59320)

**Comment by LilyAndres** [comment]
Thanks @NutrientInstitute I fixed this in the new release. I will close this issue now.

**Comment by LilyAndres** [comment]
Thanks @NutrientInstitute this issue has been fixed in the new release. All good now.
