### ISSUE TITLE
Synonyms in nutritional_components_framework.csv template overriding imported synonyms

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#130]
The synonyms in the src/ontology/templates/[nutritional_components_framework.csv ](https://github.com/CompositionalDietaryNutritionOntology/cdno/blob/master/src/ontology/templates/nutritional_components_framework.csv) are overriding the synonyms imported from ChEBI.

For example, citrulline (CHEBI:18211)
On line 981 of [nutritional_components_framework.csv ](https://github.com/CompositionalDietaryNutritionOntology/cdno/blob/master/src/ontology/templates/nutritional_components_framework.csv), the label has been input as the synonym. Using OLS look at the difference between the synonyms of this term as they appear [in CDNO](https://www.ebi.ac.uk/ols4/ontologies/cdno/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_18211) and as they appear [in ChEBI](https://www.ebi.ac.uk/ols4/ontologies/chebi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FCHEBI_18211?lang=en) (screenshots provided below), the ChEBI synonyms are missing from CDNO.

**In CDNO:**
![image](https://github.com/CompositionalDietaryNutritionOntology/cdno/assets/128626166/a873d428-3a57-4c2d-91f4-302de90c1241)

**In ChEBI:**
![image](https://github.com/CompositionalDietaryNutritionOntology/cdno/assets/128626166/040424e4-3592-4ea2-b7fe-73659aba5f01)

**Comment by LilyAndres** [comment]
Working on it, thanks.

**Comment by LilyAndres** [comment]
This issue has been solved during the latest release, I will close it now.
