### ISSUE TITLE
Dietary Fiber Ontology Working Group: Fiber term updates

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#134]
The following term requests and updates have been reviewed by the Dietary Fiber Ontology Working Group.

# Term Updates: Definition Changes

## Term Label: dietary fibre

**Current CDNO definition**: A carbohydrate that resists enzymatic digestion in the digestive systems of humans and other monogastric species.

**Proposed definition:**  A carbohydrate or associated lignin that resists hydrolytic digestion in the small intestine of humans and other monogastric species, with fermentative digestion in the large intestine.

## Term Label: soluble dietary fibre

**Current CDNO definition**: Dietary fibre which dissolves in water and is primarily fermented in the colon of monogastric animals by gut bacteria

**Proposed definition:** Dietary fibre which dissolves in water and is partially or completely fermented in the colon of monogastric animals by gut bacteria.

**Proposed synonym:** water soluble dietary fibre

## Term Label: insoluble dietary fibre

**Current CDNO definition**: Dietary fibre which does not dissolve in water and is inert to digestive enzymes in the upper gastrointestinal tract of monogastric animals.

**Proposed definition:** Dietary fibre which does not dissolve in water and is inert to digestive enzymes in the upper gastrointestinal tract of monogastric animals, with variable fermentability in the large bowel.

**Proposed synonym:** water insoluble dietary fibre

# New Terms

## soluble dietary fibre precipitate (SDFP)  

**Term Label:** soluble dietary fibre precipitate (SDFP)  

**Term Definition:** Water soluble dietary fibre which precipitates in 78% aqueous ethanol.

**Parent term:** soluble dietary fibre (CDNO:0000006)

**Source of definition:**  Barry V McCleary, Measurement of Dietary Fiber: Which AOAC Official Method of AnalysisSM to Use, Journal of AOAC INTERNATIONAL, Volume 106, Issue 4, July-August 2023, Pages 917–930, https://doi.org/10.1093/jaoacint/qsad051

## soluble dietary fibre soluble (SDFS)

**Term Label:** soluble dietary fibre soluble (SDFS)

**Term Definition:** Water soluble dietary fibre which remains soluble in 78% aqueous ethanol.

**Parent term:** soluble dietary fibre (CDNO:0000006)

**Source of definition:**  Barry V McCleary, Measurement of Dietary Fiber: Which AOAC Official Method of AnalysisSM to Use, Journal of AOAC INTERNATIONAL, Volume 106, Issue 4, July-August 2023, Pages 917–930, https://doi.org/10.1093/jaoacint/qsad051

## low molecular weight dietary fibre

**Term Label:** low molecular weight dietary fibre

**Term Definition:** Dietary fibre oligomers of degree of polymerization (DP)  > 2 which remain soluble in 78% aqueous ethanol and are not digested by enzymes of the human digestive tract.

**Parent term:** soluble dietary fibre (CDNO:0000006)

**Source of definition:**  Barry V McCleary, Measurement of Dietary Fiber: Which AOAC Official Method of AnalysisSM to Use, Journal of AOAC INTERNATIONAL, Volume 106, Issue 4, July-August 2023, Pages 917–930, https://doi.org/10.1093/jaoacint/qsad051

## high molecular weight dietary fibre

**Term Label:** high molecular weight dietary fibre

**Term Definition:** Fractions of dietary fibre calculated as the sum of water insoluble dietary fibre (IDF)(e.g. cellulose) and soluble dietary fibre that precipitates in the presence of 78% aqueous ethanol (SDFP).

**Parent term:** dietary fibre (CDNO:0000005)

**Source of definition:**  Barry V McCleary, Measurement of Dietary Fiber: Which AOAC Official Method of AnalysisSM to Use, Journal of AOAC INTERNATIONAL, Volume 106, Issue 4, July-August 2023, Pages 917–930, https://doi.org/10.1093/jaoacint/qsad051

## fermentable dietary fibre

**Term Label:** fermentable dietary fibre

**Term Definition:** Dietary fibre of degree of polymerization (DP) > 2 resistant to digestion and absorption in the human small intestine but that is partially or completely fermented by the large bowel microbiota. 

**Parent term:** dietary fibre (CDNO:0000005)

## non-fermentable dietary fibre

**Term Label:** non-fermentable dietary fibre

**Term Definition:** Dietary fibre that resists degradation by the bacteria in the colon, resulting in limited action by the large bowel microbiota. 

**Parent term:** dietary fibre (CDNO:0000005)

## viscous dietary fibre

**Term Label:** viscous dietary fibre

**Term Definition:** Soluble dietary fibre that dissolves in water to form semifluid solutions or a gel-like matrix, and exhibits high shear strength in aqueous solutions.

**Parent term:** soluble dietary fibre (CDNO:0000006)

## added dietary fibre

**Term Label:** added dietary fibre

**Term Definition:** Dietary fibre which has been isolated or synthesized and is added to the diet of humans or other monogastric species that has beneficial physiological effects.

**Parent term:** dietary fibre (CDNO:0000005)

**Source of definition:** National Academies of Sciences, Engineering, and Medicine. 2001. Dietary Reference Intakes: Proposed Definition of Dietary Fiber. Washington, DC: The National Academies Press. https://doi.org/10.17226/10161.

## prebiotic dietary fibre

**Term Label:** prebiotic dietary fibre

**Term Definition:** Dietary fibre that is selectively utilized by host microorganisms conferring a health benefit.

**Parent term:** dietary fibre (CDNO:0000005)

**Source of definition:** Gibson, G., Hutkins, R., Sanders, M. et al. Expert consensus document: The International Scientific Association for Probiotics and Prebiotics (ISAPP) consensus statement on the definition and scope of prebiotics. Nat Rev Gastroenterol Hepatol 14, 491–502 (2017). https://doi.org/10.1038/nrgastro.2017.75

**Comment by LilyAndres** [comment]
@recombics , @ddooley please have a look at these terms will need to be added next week.

**Comment by recombics** [comment]
there are ~9 terms - was unsure how to respond to them separately, so:  
dietary fibre
a) My first question is whether 'or associated lignin' fits with dietary fibre adhering to the relationship 'is a carbohydrate' (well, it seems not solely, as lignin is a plant_secondary_product ...)
b) "digestion in the small intestine of humans and other monogastric species with fermentative digestion in the large intestine." - the 'with' I assume should be: 'that have' 'having' or similar ? (ie or a comma before 'with'?)
insoluble:
'tract of monogastric animals with variable fermentability in the large bowel' - again, the with seems to be a problem. is it ' .. , with' or that the animals have variable fermentability. I assume the former, so add a comma ?
added dietary fibre:
'to the diet of humans and other monogastric'  -> 'to the diet of humans or other monogastric' ?
viscous dietary fibre:
this is also describing a physical attribute - CDNO_0400001 
NB solubility is also a physical attribute  - cf PATO_0001536 (physical object quality)

**Comment by NutrientInstitute** [comment]
- Good point when it comes to the inclusion of lignin in dietary fibre, there was a general agreement among fiber experts that lignin be included in this definition. That would mean that 'dietary fibre' would have to have parent 'dietary chemical component' instead of 'carbohydrate'
- Regarding the definitions of dietary fibre and insoluble fibre, there should be a comma before "with" - I will correct this
- The definition of added dietary fibre will be edited to use "or" instead of "and" for consistency. 
- As for viscous dietary fibre, in the future I believe we can create a new attribute called 'viscosity' with a defined relationship to viscous dietary fibre (we can do the same with PATO attribute/quality solubility and insoluble/soluble dietary fibre)

**Comment by recombics** [comment]
@NutrientInstitute    great, thanks.  I think from my (layman's) perspective it would make sense to have dietary fibre at top level under dietary chemical component.  Look forward to populating with attributes such as viscosity, alongside energy (on its way from a discussion with @ddooley and @kaiiam)

**Comment by LilyAndres** [comment]
@NutrientInstitute I will wait for your changes before I do the new release, just to make sure I have the last problems as you mentioned.

**Comment by LilyAndres** [comment]
I have incorporated these terms into the ontology, thanks @NutrientInstitute looking forward for the next updates. I will close this issue now.
