### ISSUE TITLE
Change parent of dietary fibre

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#141]
Since the definition for dietary fibre (CDNO:0000005) includes lignin, which is not a carbohydrate, the parent term for dietary fibre needs to change from carbohydrate (CHEBI:16646) to dietary chemical component (CDNO:0000001). 

The term soluble dietary fibre (CDNO:0000006), will need to be made a child of both dietary fibre and carbohydrate. This is not necessary for most of the children of dietary fibre as they are already children of polysaccharide (CHEBI:18154) which is a child of carbohydrate.

We are currently reviewing with experts to determine if carbohydrate should be added as a parent to terms:
- added dietary fibre
- fermentable dietary fibre
- high molecular weight dietary fibre
- non-fermentable dietary fibre
- prebiotic dietary fibre

If lignin is a child of any of these fibre terms, the term will remain a child of dietary fibre only. If lignin is not a child of these terms, the fiber terms will be children of both dietary fibre and carbohydrate. 

Once we have recieved feedback on lignin from fiber experts (within 2-4 weeks), I will follow-up with a pull request to impliment changes to parent terms.

**Comment by LilyAndres** [comment]
This has been solved in the latest release, please have a look and let me know if there are any issues with it. I will close this issue now.
