### ISSUE TITLE
Terms "derived from hemicellulose" are redundant

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#144]
We have recieved feedback from The Fiber Ontology Working Group that terms ending in the phrase "derived from hemicellulose" are redundant and mean the same as their parent terms.

These terms include
- arabinoxylan derived from hemicellulose (CDNO:0100009)
- glucomannan derived from hemicellulose (CDNO:0100008)
- mannan derived from hemicellulose (CDNO:0100005)
- xylan derived from hemicellulose (CDNO:0100006)
- xyloglucan derived from hemicellulose (CDNO:0100007)

**Comment by LilyAndres** [comment]
This issue has been solved in the latest release, I will close this issue now.

**Comment by ddooley** [comment]
@LilyAndres ok, will do!
