### ISSUE TITLE
Dietary Fiber Ontology Working Group: Approved Terms (10/8/24)

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#146]
Fiber terms reviewed and approved by the Dietary Fiber Ontology Working Group, will now be submitted here in small batches of 5-10 terms every week or so.

The following terms have been approved by the working group and are ready for implementation into CDNO.

________

Term label:
non-starch polysaccharide

Synonym(s):
NSP; polysaccharide, non-starch

Parent term(s):
dietary fibre; polysaccharide

Term Definition:
A polysaccharide fraction of dietary fibre that excludes lignin and all starch.

Definition source:
"Appendix B: Glossary." Institute of Medicine. 2001. Dietary Reference Intakes: Proposed Definition of Dietary Fiber. Washington, DC: The National Academies Press. PMID: [25057569](https://pubmed.ncbi.nlm.nih.gov/25057569) DOI: [10.17226/10161](http://dx.crossref.org/10.17226/10161)

________

Term label:
cellulosic polysaccharide

Synonym(s):
polysaccharide, cellulosic; non-starch cellulosic polysaccharide

Parent term(s):
non-starch polysaccharide; insoluble dietary fibre; high molecular weight dietary fibre; added dietary fibre

Term Definition:
A non-starch polysaccharide composed of cellulose or its derivatives.

Definition source:
cellulosic. 2024. In Merriam-Webster.com. Retrieved Oct 1, 2024, from https://www.merriam-webster.com/dictionary/cellulosic

Alternative definition source:
Sánchez-Romero C, Guillén R, Heredia A, Jiménez A, Fernández-Bolaños J. Degradation of hemicellulosic and cellulosic polysaccharides in pickled green olives. J Food Prot. 1998 Jan;61(1):87-93. doi: [10.4315/0362-028x-61.1.87](https://doi.org/10.4315/0362-028x-61.1.87). PMID: 9708258.

________

Term label:
non-starch non-cellulosic polysaccharide

Synonym(s):
non-cellulosic polysaccharide; polysaccharides, non-cellulosic

Parent term(s):
non-starch polysaccharide

Term definition:
A non-starch polysaccharide, other than cellulose, composed of chains of various types of monosaccharide units, that may be substituted with side chains and by various functional groups.

Definition source:
Donev E, Gandla ML, Jönsson LJ and Mellerowicz EJ (2018) Engineering Non-cellulosic Polysaccharides of Wood for the Biorefinery. Front. Plant Sci. 9:1537. doi: [10.3389/fpls.2018.01537](https://doi.org/10.3389/fpls.2018.01537)
________

Term label:
chitin

Synonym(s):
[1,4-(N-Acetyl-beta-D-glucosaminyl)]n; [4)-β-D-GlcpNAc(1→]n; beta-1,4-Poly-N-acetyl-D-glucosamine; Chitin

Parent term(s):
carbohydrate; non-starch non-cellulosic polysaccharide; high molecular weight dietary fibre; insoluble dietary fibre; added dietary fibre

Term definition:
An aminoglycan consisting of β-(1→4)-linked N-acetyl-D-glucosamine residues.

Definition source:
ChEBI ([CHEBI:17029](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17029))
________

Term label:
chitosan

Synonym(s):
[4)-β-D-GlcpN(1→]n; beta-1,4-Poly-D-glucosamine; Chitosan; Deacetylchitin; poliglusam; deacetylated chitin

Parent term(s):
carbohydrate; non-starch non-cellulosic polysaccharide; soluble dietary fibre precipitate (SDFP); high molecular weight dietary fibre; viscous dietary fibre

Term definition:
An aminoglycan consisting of β-(1→4)-linked D-glucosamine residues.

Definition source:
ChEBI ([CHEBI:16261](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16261))
________

**Comment by LilyAndres** [comment]
Thanks @NutrientInstitute I am working on this. Question, do I need to create any sugar derivatives from this?

**Comment by NutrientInstitute** [comment]
@LilyAndres We do not have any "derives from" relationships to share at this time. We are currently fouced on direct parent-child relationships, but will pass on any feedback we may recieve on the derivation of fiber terms.

**Comment by LilyAndres** [comment]
Ok @NutrientInstitute thanks. I have added the new terms, I didn't add 'chitosan' because it already exist [CHEBI_16261] and [CDNO_0200719].

**Comment by LilyAndres** [comment]
This issue has been solved in the latest release, I will close it now.
