### ISSUE TITLE
Dietary Fiber Ontology Working Group: Approved terms (11/8/24)

### ISSUE THREAD

**Issue by NutrientInstitute** [CompositionalDietaryNutritionOntology/cdno#148]
The following terms have been approved by the Dietary Fiber Ontology Working Group and are ready for implementation into CDNO.

________

Term label:
pullulan

Parent term(s):
non-starch non-cellulosic polysaccharide (CDNO:0000043); glucan (CHEBI:37163)

Term Definition:
A linear α-glucan composed of repeating α-1,4-linked maltotriose or maltotetraose subunits, connected by α-1,6-glycosidic bonds.

Definition source:
Muhammad Wajid Ullah, Mazhar Ul-Islam, Taous Khan, Joong Kon Park. Chapter 31 - Recent developments in the synthesis, properties, and applications of various microbial polysaccharides.
Editor(s): Glyn O. Phillips, Peter A. Williams. In Woodhead Publishing Series in Food Science, Technology and Nutrition. Handbook of Hydrocolloids (Third Edition). Woodhead Publishing. 2021. Pages 975-1015. ISBN 9780128201046. https://doi.org/10.1016/B978-0-12-820104-6.00032-2.
(https://www.sciencedirect.com/science/article/pii/B9780128201046000322)

________

Term label:
modified cellulose

Parent term(s):
cellulosic polysaccharide (CDNO:0000042)

Term Definition:
A cellulosic polysaccharide to which substituent groups have been added.

Definition source:
Aziz T, Farid A, Haq F, Kiran M, Ullah A, Zhang K, Li C, Ghazanfar S, Sun H, Ullah R, Ali A, Muzammal M, Shah M, Akhtar N, Selim S, Hagagy N, Samy M, Al Jaouni SK. A Review on the Modification of Cellulose and Its Applications. Polymers (Basel). 2022 Aug 5;14(15):3206. doi: 10.3390/polym14153206. PMID: 35956720; PMCID: PMC9371096.
________

Term label:
chitin-glucan

Synonym(s):
Chitin-glucan complex; CGC; CG

Parent term(s):
non-starch non-cellulosic polysaccharide (CDNO:0000043)

Term Definition:
A non-starch polysaccharide composed of chitin (β-1,4-poly-N-acetyl-D-glucosamine) and β-1,3-D-glucan, obtained from Aspergillus niger mycelial cell walls.

Definition source:
Calatayud M, Verstrepen L, Ghyselinck J, Van den Abbeele P, Marzorati M, Modica S, Ranjanoro T, Maquet V. Chitin Glucan Shifts Luminal and Mucosal Microbial Communities, Improve Epithelial Barrier and Modulates Cytokine Production In Vitro. Nutrients. 2021 Sep 18;13(9):3249. doi: 10.3390/nu13093249. PMID: 34579126; PMCID: PMC8467507.
________

Term label:
nondigestible oligosaccharide

Synonym(s):
Oligosaccharide, nondigestible; Resistant Oligosaccharide

Parent term(s):
dietary fibre (CDNO:0000005); oligosaccharide (CHEBI:50699)

Term Definition:
A dietary fiber consisting of 3-9 monomeric units not digested by enzymes of the human digestive tract and soluble in water.

Definition source:
Møller A., Unwin I.D., Ireland J., Roe M.A, Becker W., Colombani P., Machackova, M. . EuroFIR Thesauri: Component thesaurus, Version 1.6. [Internet dataset]. European Food Information Resource (EuroFIR); 2022 May 25 [accessed 2023 Dec 5]. Available from: https://www.eurofir.org/our-resources/eurofir-thesauri/
________

Term label:
ajugose (CHEBI:28554)

*term is to be imported from ChEBI with no change to definition*

Parent term(s):
nondigestible oligosaccharide; hexasaccharide (CHEBI:35368)

________

**Comment by LilyAndres** [comment]
Ok, five new terms have been created. I will close this issue now, thanks @NutrientInstitute
